In [1]:
import sqlite3
import os

In [2]:
path = os.path.realpath('../Data')
con = sqlite3.connect(path+"/RecipeDB.db")
cur = con.cursor()

In [27]:

sql1 = """
    select recID from Recipe where recDisc = ""
    or recSteps = 0
    or recLink is NULL
    or recName like "%test%"
"""
sqlDelAlleInRec = """
    Delete from AlleInRec where recID = ?;
"""
sqlDelIngInRec = """
    Delete from IngInRec where recID = ?;
"""
sqlDelNutrInRec = """
    Delete from NutrInRec where recID = ?;
"""
sqlDelStepsInRec = """
    Delete from StepsInRec where recID = ?;
"""
sqlDelTagsInRec = """
    Delete from TagsInRec where recID = ?;
"""
for id in cur.execute(sql1).fetchall():
    cur.execute(sqlDelAlleInRec, id)
    cur.execute(sqlDelIngInRec, id)
    cur.execute(sqlDelNutrInRec, id)
    cur.execute(sqlDelStepsInRec, id)
    cur.execute(sqlDelTagsInRec, id)
    print(id)
    

sql1 = """
    Delete from Recipe where recDisc = ""
    or recSteps = 0
    or recLink is NULL
    or recName like "%test%"
"""
cur.execute(sql1)

con.commit()
con.close()

('5252b0fb301bbf46038b46a5',)
('525d0a56301bbf2a038b456b',)
('525d0ce2301bbf2b038b456d',)
('52b054e2453bc0eaec8b4567',)
('52ea6a0c453bc082398b4567',)
('52ea6aad453bc09a398b4567',)
('5305df86453bc00dee8b4567',)
('54047370ff604da07d8b4569',)
('5576d59af8b25e5c6a8b4567',)
('55eda88779a23cfb418b4567',)
('56c43ccef8b25e04158b4569',)
('57305eb2f8b25e34148b4567',)
('5731d62e4dab71626b8b4567',)
('5731d848fd2cb967798b4567',)
('57441a8ff8b25e10478b4567',)
('577bb95377d68d912c8b4568',)
('577cfe44518c88cb238b4568',)
('578e050313e9d6b85f8b4568',)
('578e05b4518c88d90c8b4568',)
('578e0691b5793fc1418b4568',)
('578e07c8f31cf13e758b4568',)
('578e08bd16a86616418b4568',)
('578e09d47417fee0698b4568',)
('57adeac0518c885d2b8b4568',)
('57bd7052f31cf140308b4568',)
('57cd7e97544b18115f8b4569',)
('57e157a7383a7f552e0da562',)
('57fcda72cc7bd04ee90482b2',)
('583442199f236a18327b9d82',)
('583547e82e69d7284f746f52',)
('58354dac4348d26e55071e92',)
('58355ad6b32fbe26e602f3f2',)
('58355cbab32fbe2668789902',)
('58988e7b8e8c6104356ed4f3',)
('58a2f2d73131002c41367f03',)
('58aeead1d56afa79fc566073',)
('58b814244f78db7ded7b8c02',)
('58c7f571043c3c042a5d8742',)
('58d185552310a865ae0e5cd3',)
('58de65b551d3f17bff7d4c43',)
('58f6157dc9fd082c1b57e562',)
('58f72ff8c9fd084f627dbb82',)
('58f9effcd0d6bd7a5879b6b3',)
('58f9f19d2310a877f47ba0f2',)
('5900436151d3f11aa25f0973',)
('5904a3fbc9fd087f8b26ae72',)
('5904a4bfc6243b724845c752',)
('5904a5f6d56afa549c1e9e82',)
('5904afc3d0d6bd1e017faec2',)
('5904afe151d3f10af2595543',)
('5904afecd56afa4470503d22',)
('5904b004c6243b58251ddbc3',)
('5906dd92313100446d1e4673',)
('5906ddad3bddb53aa50c4be2',)
('5906ddb331310046273bf7a2',)
('5906e3cb99052d4e7d211ba2',)
('5906e3dc2310a8705045ec62',)
('5906e3ebd0d6bd6cbf3f5842',)
('591b04fe313100759c174fe2',)
('591b05834f78db44df498223',)
('594792042310a86a8205eb62',)
('597739e6ad1d6c2eaf06fe32',)
('5981a99aa2882a054b7f6123',)
('59e8769e053468047c4a8d12',)
('59e8890c7901f936b906ee42',)
('59e88c2d7cc0c166d9322c42',)
('59e88f57c94eac59ca383082',)
('5ab2977aae08b5569b3b1572',)
('5b06c86030006c59a7572e61',)
('5b06caba30006c5b10791a72',)
('5b06cc4b30006c5c1430a722',)
('5b0c1664ae08b5208c398092',)
('5b0c183130006c15960ed312',)
('5b89638eae08b513d81d8792',)
('5ba0cee230006c75fb05dbb2',)
('5bc6ea15ae08b56d647148b2',)
('5bf2afb1ae08b57cde2cae72',)
('5c0e6529c445fa60331be0a1',)
('5c0e759fc445fa6e92425a42',)
('5c13dd7de3f33910df6551a2',)
('5c17696be3f339693b08fde2',)
('5c176b6ee3f3396a9a6005c2',)
('5c176e04e3f3396c1579da62',)
('5c190703c445fa124e526722',)
('5c190747c445fa1278030de2',)
('5c190759e3f33911917f8202',)
('5c190770c445fa1280650f72',)

In [30]:
sql2 = """
    Update Recipe set recRating = 0.0,
    recRatingCount = 0 
    where recRating is NULL
    and recRatingCount is NULL;
"""

cur.execute(sql2)
con.commit()

In [31]:
sql3 = """
    select recID from Recipe where recPrepTime is NULL
"""
sqlDelAlleInRec = """
    Delete from AlleInRec where recID = ?;
"""
sqlDelIngInRec = """
    Delete from IngInRec where recID = ?;
"""
sqlDelNutrInRec = """
    Delete from NutrInRec where recID = ?;
"""
sqlDelStepsInRec = """
    Delete from StepsInRec where recID = ?;
"""
sqlDelTagsInRec = """
    Delete from TagsInRec where recID = ?;
"""
for id in cur.execute(sql3).fetchall():
    cur.execute(sqlDelAlleInRec, id)
    cur.execute(sqlDelIngInRec, id)
    cur.execute(sqlDelNutrInRec, id)
    cur.execute(sqlDelStepsInRec, id)
    cur.execute(sqlDelTagsInRec, id)
    print(id)
    

sql3 = """
    Delete from Recipe where recPrepTime is NULL
"""
cur.execute(sql3)

con.commit()

('57b2c998f31cf16a518b4568',)
('57e13c75518c88f90b8b4568',)
('57e15e704cdfb530de706cd3',)
('5a684d44d56afa1b286616b3',)

In [37]:
def to_Int(s) :
    if not s:
        return 0
    return int( "".join(x for x in s if x.isdigit()))
sql5 = "Select recID, recPrepTime, recTotalTime from Recipe"

sql6 = "Update Recipe set recTime = ? where recID = ?"
for t in cur.execute(sql5).fetchall():
    time = to_Int(t[1]) + to_Int(t[2])
    cur.execute(sql6, (time, t[0]))
con.commit()

In [ ]:
sql1 = """
        select recID as id from Recipe
        WHERE id NOT IN(
        SELECT  MIN(recID) as id
        FROM Recipe
        GROUP BY recName, recHeadline);
"""
sqlDelAlleInRec = """
    Delete from AlleInRec where recID = ?;
"""
sqlDelIngInRec = """
    Delete from IngInRec where recID = ?;
"""
sqlDelNutrInRec = """
    Delete from NutrInRec where recID = ?;
"""
sqlDelStepsInRec = """
    Delete from StepsInRec where recID = ?;
"""
sqlDelTagsInRec = """
    Delete from TagsInRec where recID = ?;
"""
for id in cur.execute(sql1).fetchall():
    cur.execute(sqlDelAlleInRec, id)
    cur.execute(sqlDelIngInRec, id)
    cur.execute(sqlDelNutrInRec, id)
    cur.execute(sqlDelStepsInRec, id)
    cur.execute(sqlDelTagsInRec, id)
    #print(id)
    

sql1 = """
    Delete from Recipe
    WHERE recID NOT IN(
    SELECT  MIN(recID) as recID
    FROM Recipe
    GROUP BY recName, recHeadline);
"""
cur.execute(sql1)

con.commit()

In [3]:
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import CountVectorizer
 
from sklearn.feature_extraction.text import TfidfVectorizer
 
from sklearn.metrics.pairwise import cosine_similarity

%matplotlib inline

In [4]:
con = sqlite3.connect(path+"/RecipeDB.db")

sql = " SELECT * FROM IngFamily; "

ing_df = pd.read_sql(sql,con)
df = pd.read_sql("Select * From Ingredients", con)
ing_df.head()

                   familyID familyName
0  58877cf3ed71a76e9c03fc1c       Reis
1  58877cf3ed71a76e9c03fb54       Brot
2  58877cf3ed71a76e9c03fc4e      Essig
3  58877cf3ed71a76e9c03fb3b  Aubergine
4  58877cf3ed71a76e9c03fc47   Truthahn

In [20]:
dupice = ing_df[ing_df.duplicated(subset= ['familyName'])]
dupice

                     familyID   familyName
156  58877cf3ed71a76e9c03fc15       Kürbis
208  58877cf3ed71a76e9c03fbea     Olivenöl
210  5901b0d4c6243b746b6221f2  Rindfleisch
215  58877cf3ed71a76e9c03fb70    Chilisoße
216  58877cf3ed71a76e9c03fb9d        Fisch
219  58877cf3ed71a76e9c03fc31    Sojasauce
224  58877cf3ed71a76e9c03fc3d         Mais

In [22]:
df_du = pd.merge(df, dupice, on='familyID')
df_du

,ingID,ingName,familyID,familyName
0,55cb734f4dab71420d8b4568,Kürbis (Hokkaido),58877cf3ed71a76e9c03fc15,Kürbis
1,5b57468f30006c10552b3d72,"Hokkaido-Kürbis, gewürfelt",58877cf3ed71a76e9c03fc15,Kürbis
2,592a6b3bd56afa69ef25b222,(Oliven-)Öl*,58877cf3ed71a76e9c03fbea,Olivenöl
3,590b4dbb2310a805862c8922,vorgegarte Rote Bete,5901b0d4c6243b746b6221f2,Rindfleisch
4,5a31131f2c3e0876d2056ed2,TABASCO® Chipotle Sauce,58877cf3ed71a76e9c03fb70,Chilisoße
5,5ab9dc6230006c2ddc01a951,Alaska-Seelachs,58877cf3ed71a76e9c03fb9d,Fisch
6,5ad06bc2ae08b5693d312d42,Garnelen,58877cf3ed71a76e9c03fb9d,Fisch
7,5b8e553530006c578a4c74f2,Seehecht,58877cf3ed71a76e9c03fb9d,Fisch
8,5b55e926ae08b5134d24f773,Ketjap Manis,58877cf3ed71a76e9c03fc31,Sojasauce
9,5bc6f8f230006c59c1222582,Karamellbonbons,58877cf3ed71a76e9c03fc3d,Mais

duplicated manuell entfernt